export const SET_VISIBLE_PASSWORD = "SET_VISIBLE_PASSWORD";
export const POST_REGISTER_SUCCES = "POST_REGISTER_SUCCES";
export const POST_REGISTER_ERROR = "POST_REGISTER_ERROR";
export const POST_SINGIN_SUCCES = "POST_SINGIN_SUCCES";
export const POST_SINGIN_ERROR = "POST_SINGIN_ERROR";

export const GET_OWN_USER_SUCCESS = "GET_OWN_USER_SUCCESS";
export const GET_OWN_USER_ERROR = "GET_OWN_USER_ERROR";
export const NEW_CARD_SUCCES = "NEW_CARD_SUCCES";
export const NEW_CARD_ERROR = "NEW_CARD_ERROR";

export const GET_RESTAURANTS_SUCCESS = "GET_RESTAURANTS_SUCCESS"
export const GET_RESTAURANTS_ERROR = "GET_RESTAURANTS_ERROR"

export const SET_SEARCH_CATEGORY_RESTAURANTS = "SET_SEARCH_CATEGORY_RESTAURANTS"